// Code generated by "enumer -type=Color -yaml"; DO NOT EDIT

package Spinner

import (
	"fmt"
)

const _Color_name = "REDBLUEMIX"

var _Color_index = [...]uint8{0, 3, 7, 10}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}

var _ColorNameToValue_map = map[string]Color{
	_Color_name[0:3]:  0,
	_Color_name[3:7]:  1,
	_Color_name[7:10]: 2,
}

func ColorString(s string) (Color, error) {
	if val, ok := _ColorNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Color values", s)
}

func (i Color) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

func (i *Color) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ColorString(s)
	return err
}
