// Code generated by "enumer -type=Coordinates -yaml"; DO NOT EDIT

package Spinner

import (
	"fmt"
)

const _Coordinates_name = "POLARCARTESIAN"

var _Coordinates_index = [...]uint8{0, 5, 14}

func (i Coordinates) String() string {
	if i < 0 || i >= Coordinates(len(_Coordinates_index)-1) {
		return fmt.Sprintf("Coordinates(%d)", i)
	}
	return _Coordinates_name[_Coordinates_index[i]:_Coordinates_index[i+1]]
}

var _CoordinatesNameToValue_map = map[string]Coordinates{
	_Coordinates_name[0:5]:  0,
	_Coordinates_name[5:14]: 1,
}

func CoordinatesString(s string) (Coordinates, error) {
	if val, ok := _CoordinatesNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Coordinates values", s)
}

func (i Coordinates) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

func (i *Coordinates) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CoordinatesString(s)
	return err
}
